import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import ThemeToggle from "./ui/ThemeToggle";
import Link from "next/link";
import ThemeProvider from "./ui/theme/theme-provider";
import ThemeToggle from "./ui/theme/theme-toggle";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="overflow-hidden text-text dark:text-dark-text bg-background dark:bg-dark-background min-h-[100vh]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="bg-surface dark:bg-dark-surface flex justify-between items-center px-[30px] w-[100%] ">
            <Link
              href="/"
              className=" max-w-[200px] title bg-blue-400 
          rounded-3xl ml-10 my-auto flex justify-center items-center
         "
            >
              <span className="my-auto py-3 text-2xl font-bold text-white">
                Saiga-English
              </span>
            </Link>
            <ul className="grid grid-cols-4 subtitle  h-[70px] justify-items-center items-center bg-yellow-300">
              <Link href={"/"}>Главная</Link>
              <Link href={"/decks"}>Колоды</Link>
              <Link href={"/about"}>О нас</Link>
              <Link className="text-nowrap" href={"/results"}>
                Мои результаты
              </Link>
            </ul>
            <div className="flex flex-nowrap gap-x-[40px]">
              <Link
                className="flex justify-center items-center border-b-2 px-1 border-text dark:border-dark-text"
                href={"sign-in"}
              >
                Войти
              </Link>
              <ThemeToggle />
            </div>
          </header>
          <div className=" pt-[150px]   flex justify-center  align-middle bg-background dark:bg-dark-background ">
            <div className="max-w-[1280px]  w-[100%] h-[100%]"> {children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
